### ISSUE TITLE
Error: Request timed out before a satisfactory answer was given

### ISSUE THREAD

**Issue by spidy0x0** [westh/serial-commander#9] opened 2022-05-06 02:28 UTC
hi, i just installed this repo . then i tried running this
```
const SerialCommander = require('@westh/serial-commander') // or use import ... from ...

const serialCommander = new SerialCommander({
  port: '/dev/ttyUSB0', // defaults to /dev/modem
  baudrate: 9600, // defaults to 115200
  readDelimiter : '\r', // defaults to '/n'
  writeDelimiter : '\n', // defaults to '/r/n'
  disableLog: false, // defaults to false
  defaultDelay: 50, // delay [ms] before the command is issued defaults to 100
  log: string => console.log(`[${new Date().toISOString()}] ${string}`) // default logging function
})

async function main () {
  const options = {
    expectedResponses: ['OK', 'YEAH'], // defaults to ['OK']
    timeout: 500,  // defaults to 1000
    delay: 100 // defaults to defaultDelay set in the constructor
  }
  const response = await serialCommander.send('AT+CUSD=1,"*124#",15', options)
  console.log(response)
  serialCommander.close()
}

main()
```
and then i am getting this error
```
[2022-05-06T02:18:18.163Z] >> AT+CUSD=1,"*124#",15
.../node_modules/@westh/serial-commander/lib/cjs/index.js:54
        reject(new Error('Request timed out before a satisfactory answer was given'));
               ^

Error: Request timed out before a satisfactory answer was given
    at Timeout._onTimeout (.../node_modules/@westh/serial-commander/lib/cjs/index.js:54:16)

```
Any way to solve this issue?

**Comment by westh** [comment] 2022-05-24 06:16
👋 Hi @spidyhackx,

It's hard to say what is going on from the logs you've sent. The error indicates that a response matching one of the responses specified in the `options.expectedResponses` field hasn't been sent over the port within the timeframe specified in `options.timeout`.

The root cause of this could be multiple things, e.g. the timeout being too short, having specified the wrong port, or the modem not responding because of misconfiguration or internal reasons.

The first thing I'd check would be to try and send a simple `AT` to check if the modem responds, i.e. `const response = await serialCommander.send('AT', options)`. If that doesn't work then check that you are using the right port and check the modem itself. If/when the simple `AT` call and response work then I'd try again, and if the issue still persists then I'd consult the documentation for the particular modem to see what it is supposed to respond to the command and if there are any time restraints specified.

Hope it works out for you : )

**Comment by westh** [comment] 2022-06-21 09:45
It's been almost a month so I'm closing this one, open a new one if you're still having issues ✌️

**Closed as completed by westh** 2022-06-21 09:45 UTC
